version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - shared-network
    environment:
      - JWT_SECRET=fddasasfsdfgasasgsdagfdfasd
      - EXPIRES_IN=1
      - TRAVELS_API=https://z0qw1e7jpd.execute-api.eu-west-1.amazonaws.com/default/trips
      - TRAVELS_API_KEY=fgy6fd9I316DSDD090Shj4eG1DUxuxpI8sZlAOg1
      - MONGO_URL=mongodb://mongo:27017/trip-planner
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=myRedisPassword
      - APP_PORT=3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - shared-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared-network
    command: redis-server --requirepass myRedisPassword
volumes:
  mongo-data:

networks:
  shared-network: